### Makefile for Grupo_N Webots controller
### Works on Windows, macOS and Linux.
### On Linux with snap Webots, run:
###   WEBOTS_HOME=/snap/webots/current/usr/share/webots make

null :=
space := $(null) $(null)
WEBOTS_HOME_PATH?=$(subst $(space),\ ,$(strip $(subst \,/,$(WEBOTS_HOME))))
include $(WEBOTS_HOME_PATH)/resources/Makefile.include
